name: Email Verification Workflow


on:
  push:
    branches:
      - main


jobs:
  test:
    
    runs-on: ubuntu-latest

    
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: 23f2002898@ds.study.iitm.ac.in
        run: |
          echo "This step contains the required email address in its name."
          echo "Current date and time: $(date)"


      - name: Final Confirmation
        run: echo "Workflow execution completed."
