name: Combined Verification and Caching Tasks

on:
  push:
    branches:
      - main

jobs:
  email_verification_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 23f2002898@ds.study.iitm.ac.in
        run: echo "Verifying required step name for task 1."

  caching_and_check_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: prime-cache-eed60d55
        uses: actions/cache@v4
        id: cache-step 
        with:
          key: cache-eed60d55
          path: ~/.npm 

      - name: Echo Cache Result
        run: |
          # The actions/cache step sets an output variable 'cache-hit'.
          if [ "${{ steps.cache-step.outputs.cache-hit }}" == "true" ]; then
            echo "Cache Status: HIT 🎉"
          else
            echo "Cache Status: MISS 💔 (Priming cache...)"
          fi
